
# Dataset
NUM_CLASSES = 20
IMG_SIZE = 224
BATCH_SIZE = 32

#Training
NUM_EPOCHS = 20
LEARNING_RATE = 0.001

#Reproducibility
SEED = 42

CLASS_NAMES = [
    'ABBOTTS BABBLER', 'ABBOTTS BOOBY', 'ABYSSINIAN GROUND HORNBILL',
    'AFRICAN CROWNED CRANE', 'AFRICAN EMERALD CUCKOO', 'AFRICAN FIREFINCH',
    'AFRICAN OYSTER CATCHER', 'AFRICAN PIED HORNBILL', 'AFRICAN PYGMY GOOSE',
    'ALBATROSS', 'ALBERTS TOWHEE', 'ALEXANDRINE PARAKEET', 'ALPINE CHOUGH',
    'ALTAMIRA YELLOWTHROAT', 'AMERICAN AVOCET', 'AMERICAN BITTERN',
    'AMERICAN COOT', 'AMERICAN FLAMINGO', 'AMERICAN GOLDFINCH', 'AMERICAN KESTREL'
]

# EfficientNet fine-tuning
EFFICIENTNET_STAGE1_EPOCHS = 5
EFFICIENTNET_STAGE2_EPOCHS = 10
EFFICIENTNET_STAGE1_LR     = 0.001
EFFICIENTNET_STAGE2_LR     = 0.0001