"""add analysis_reports table

Revision ID: 4176aa602528
Revises: 17243222cda5
Create Date: 2026-08-02 23:01:47.323524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4176aa602528'
down_revision: Union[str, Sequence[str], None] = '17243222cda5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('filter_species_id', sa.Integer(), nullable=True),
    sa.Column('filter_source', sa.String(), nullable=True),
    sa.Column('filter_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filter_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('prediction', sa.String(), nullable=True),
    sa.Column('pattern_table', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_reports')
    # ### end Alembic commands ###
